name: CI

on:
  push:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nightly Rust
        run: rustup toolchain install nightly

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Rust server
        run: |
          git clone https://github.com/uselessgoddess/rust-server
          cd rust-server
          cargo +nightly build --release
      - name: Build Go server
        run: |
          git clone https://github.com/uselessgoddess/goServer

      - name: Run Rust server
        run: |
          cd rust-server
          cargo +nightly run --release &
          cd ..
          cargo +nightly run --release -- 1234
      - name: Run Go server
        run: |
          cd goServer
          go env -w GO111MODULE=off
          go mod download github.com/99designs/gqlgen
          go mod download github.com/agnivade/levenshtein
          go get github.com/99designs/gqlgen/graphql/handler/transport@v0.14.0
          go get github.com/99designs/gqlgen/graphql/handler/lru@v0.14.0
          go get github.com/99designs/gqlgen/graphql/handler/extension@v0.14.0
          go get github.com/99designs/gqlgen/graphql@v0.14.0
          go get github.com/99designs/gqlgen/graphql/handler@v0.14.0
          go get github.com/99designs/gqlgen/graphql/executor@v0.14.0
          go get github.com/99designs/gqlgen/graphql/executor@v0.14.0
          sudo go run server.go &
          cd ..
          cargo +nightly run --release -- 4321
